# Generated by Django 3.0.3 on 2020-06-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('categeory', models.CharField(max_length=50)),
            ],
        ),
    ]
