# Generated by Django 3.0.3 on 2020-06-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='logintime',
            field=models.CharField(default=100, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='register',
            name='fullname',
            field=models.CharField(max_length=50),
        ),
    ]
